"use client";
import { useEffect, useMemo, useState } from "react";
import type { BusinessRecord } from "../lib/types";
import { emptyBusiness } from "../lib/types";
const fields: [keyof typeof emptyBusiness, string][] = [["name", "Business name"], ["slug", "Slug / URL"], ["heroEyebrow", "Hero eyebrow"], ["heroHeadline", "Hero headline"], ["heroSecondary", "Hero secondary text"], ["category", "Category"], ["description", "Short description"], ["locationLabel", "Location label"], ["address", "Full address"], ["phone", "Phone"], ["whatsapp", "WhatsApp number"], ["whatsappMessage", "WhatsApp message"], ["instagram", "Instagram URL"], ["tiktok", "TikTok URL"], ["facebook", "Facebook URL"], ["website", "Website URL"], ["mapsUrl", "Google Maps URL"], ["storeHeading", "Store heading"], ["storeStatus", "Store status"], ["footerText", "Footer text"]];
export default function AdminPanel({ authenticated }: { authenticated: boolean }) {
  const [logged, setLogged] = useState(authenticated), [password, setPassword] = useState(""), [items, setItems] = useState<BusinessRecord[]>([]), [editing, setEditing] = useState<Partial<BusinessRecord> | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const load = async () => { const r = await fetch("/api/businesses"); if (r.ok) setItems(await r.json()); }; useEffect(() => { if (logged) void load(); }, [logged]); const form = useMemo(() => ({ ...emptyBusiness, ...editing }), [editing]);
  async function login(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!r.ok) return setMessage("Mot de passe incorrect"); setLogged(true); setPassword(""); }
  async function upload(file: File, kind: "logo" | "store") { const data = new FormData(); data.set("file", file); data.set("slug", String(form.slug || "business")); data.set("kind", kind); const r = await fetch("/api/upload", { method: "POST", body: data }); const json = await r.json(); if (!r.ok) throw new Error(json.error); setEditing((old) => ({ ...old, [`${kind}Url`]: json.url })); }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); const r = await fetch("/api/businesses", { method: form.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const json = await r.json(); setBusy(false); if (!r.ok) return setMessage(json.error || "Erreur"); setMessage("Carte enregistrée et publiée."); setEditing(null); await load(); }
  async function remove(id: string) { if (!confirm("Supprimer cette carte ?")) return; await fetch("/api/businesses", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); await load(); }
  if (!logged) return <main className="admin-shell"><form className="login-card" onSubmit={login}><span className="platform-kicker">NFC BUSINESS CARDS</span><h1>Admin Panel</h1><p>Espace privé de gestion.</p><input type="password" placeholder="Mot de passe admin" value={password} onChange={(e) => setPassword(e.target.value)} autoFocus /><button className="platform-button" type="submit">Se connecter</button>{message && <small className="form-error">{message}</small>}</form></main>;
  return <main className="admin-shell"><div className="admin-top"><div><span className="platform-kicker">NFC BUSINESS CARDS</span><h1>Admin Panel</h1><p>Créez et gérez vos cartes clients.</p></div><div className="admin-top-actions"><button type="button" className="ghost-button" onClick={() => setEditing({ ...emptyBusiness })}>+ Nouvelle business</button><button type="button" className="ghost-button" onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); setLogged(false); }}>Quitter</button></div></div>{message && <div className="admin-message">{message}</div>}{editing ? <form className="business-form" onSubmit={save}><div className="form-header"><div><span className="platform-kicker">{form.id ? "MODIFIER" : "NOUVELLE CARTE"}</span><h2>{form.name || "Business sans nom"}</h2></div><button type="button" className="ghost-button" onClick={() => setEditing(null)}>Annuler</button></div><div className="upload-grid"><label className="upload-box">{form.logoUrl ? <img src={form.logoUrl} alt="Logo preview" /> : <span>Logo<br /><small>Choisir une image</small></span>}<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && upload(e.target.files[0], "logo")} /></label><label className="upload-box wide">{form.storeImageUrl ? <img src={form.storeImageUrl} alt="Store preview" /> : <span>Store image<br /><small>Hero + boutique</small></span>}<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && upload(e.target.files[0], "store")} /></label></div><div className="form-grid">{fields.map(([key, label]) => <label key={String(key)}>{label}<input value={String(form[key] || "")} onChange={(e) => setEditing((old) => ({ ...old, [key]: e.target.value }))} placeholder={label} /></label>)}<label>Primary color<input type="color" value={String(form.primaryColor)} onChange={(e) => setEditing((old) => ({ ...old, primaryColor: e.target.value }))} /></label><label>Accent color<input type="color" value={String(form.secondaryColor)} onChange={(e) => setEditing((old) => ({ ...old, secondaryColor: e.target.value }))} /></label></div><button className="platform-button" disabled={busy || !form.logoUrl || !form.storeImageUrl} type="submit">{busy ? "Enregistrement…" : "Créer / publier"}</button></form> : <section className="business-list"><div className="list-heading"><h2>Businesses</h2><span>{items.length} carte(s)</span></div>{items.length === 0 ? <div className="empty-admin">Aucune carte. Cliquez sur « Nouvelle business » pour commencer.</div> : items.map((item) => <article className="business-row" key={item.id}><img src={item.logoUrl} alt="" /><div><strong>{item.name}</strong><span>/{item.slug}</span></div><a href={`/${item.slug}`} target="_blank" rel="noreferrer">Ouvrir</a><button type="button" onClick={() => setEditing(item)}>Modifier</button><button type="button" onClick={() => remove(item.id)}>Supprimer</button></article>)}</section>}</main>;
}
