"use client";
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useState } from "react";
import { ArrowUpRight, ChevronRight, Copy, Map, MapPin, Phone, QrCode, Share2, UserRoundPlus, X } from "lucide-react";
import QRCode from "qrcode";
import type { BusinessRecord } from "../lib/types";

export default function BusinessCard({ business }: { business: BusinessRecord }) {
  const [qr, setQr] = useState(""); const [open, setOpen] = useState(false); const [toast, setToast] = useState("");
  const notify = useCallback((message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2300); }, []);
  useEffect(() => { if (!open) return; const fn = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false); document.body.classList.add("modal-open"); window.addEventListener("keydown", fn); return () => { document.body.classList.remove("modal-open"); window.removeEventListener("keydown", fn); }; }, [open]);
  const copy = useCallback(async (value: string, message: string) => { try { await navigator.clipboard.writeText(value); } catch { const area = document.createElement("textarea"); area.value = value; area.style.position = "fixed"; area.style.opacity = "0"; document.body.appendChild(area); area.select(); document.execCommand("copy"); area.remove(); } notify(message); }, [notify]);
  const saveContact = useCallback(() => { const vcard = ["BEGIN:VCARD", "VERSION:3.0", `FN:${business.name}`, `ORG:${business.name}`, `TEL;TYPE=WORK,VOICE:${business.phone}`, `ADR;TYPE=WORK:;;${business.address.replaceAll(",", "\\,")};;;;`, `NOTE:${business.description}`, "END:VCARD"].join("\r\n"); const url = URL.createObjectURL(new Blob([vcard], { type: "text/vcard;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${business.slug}.vcf`; a.click(); URL.revokeObjectURL(url); notify("Contact prêt à être enregistré"); }, [business, notify]);
  const share = async () => { const url = window.location.href; try { if (navigator.share) await navigator.share({ title: business.name, text: business.description, url }); else await copy(url, "Lien copié"); } catch (e) { if (!(e instanceof DOMException && e.name === "AbortError")) await copy(url, "Lien copié"); } };
  const openQr = async () => { setOpen(true); setQr(""); setQr(await QRCode.toDataURL(window.location.href, { width: 420, margin: 2, color: { dark: "#111", light: "#fff" } })); };
  const socials = [["Instagram", business.instagram, "Nos nouveautés", "social-instagram"], ["TikTok", business.tiktok, "Nos vidéos", "social-tiktok"], ["Facebook", business.facebook, "Notre communauté", "social-facebook"], ["Site web", business.website, "Visiter le site", "social-website"]].filter((item) => item[1]);
  return <main className="digital-card" style={{ "--brand": business.primaryColor, "--accent": business.secondaryColor } as React.CSSProperties}>
    <section className="hero"><img className="hero-photo" src={business.storeImageUrl} alt={business.name} /><div className="hero-shade" /><div className="hero-brand">{business.name}</div><div className="hero-copy"><span>{business.heroEyebrow}</span><strong>{business.heroHeadline}</strong><small>{business.heroSecondary}</small></div><div className="hero-curve" /></section>
    <section className="identity"><div className="brand-medallion"><img src={business.logoUrl} alt={business.name} /><span className="verified" aria-label="Commerce vérifié">✓</span></div><h1>{business.name}</h1><p className="category">{business.category}</p><p className="description">{business.description}</p>{business.mapsUrl ? <a className="location-line" href={business.mapsUrl} target="_blank" rel="noreferrer"><MapPin aria-hidden="true" /> {business.locationLabel}</a> : <p className="location-line"><MapPin aria-hidden="true" /> {business.locationLabel}</p>}</section>
    <section className="primary-actions"><a className="action-card whatsapp" href={`https://wa.me/${business.whatsapp.replace(/\D/g, "")}?text=${encodeURIComponent(business.whatsappMessage)}`} target="_blank" rel="noreferrer"><span className="whatsapp-mark">☎</span><span><strong>WhatsApp</strong><small>Discuter maintenant</small></span><ChevronRight /></a><a className="action-card call" href={`tel:${business.phone}`}><span className="action-icon"><Phone /></span><span><strong>Appeler</strong><small>{business.phone}</small></span><ChevronRight /></a><button className="action-card save" type="button" onClick={saveContact}><span className="action-icon"><UserRoundPlus /></span><span><strong>Enregistrer</strong><small>Dans vos contacts</small></span><ChevronRight /></button></section>
    {socials.length > 0 && <section className="content-section social-section"><div className="section-heading"><h2>Nos réseaux sociaux</h2><span>Suivez-nous</span></div><div className="social-grid">{socials.map(([label, url, note, cls]) => <a key={label} href={url} target="_blank" rel="noreferrer" className="social-card"><span className={`social-icon ${cls}`}>{label === "Facebook" ? "f" : label === "TikTok" ? "♪" : label === "Site web" ? "↗" : "◎"}</span><ArrowUpRight className="social-arrow" /><strong>{label}</strong><small>{note}</small></a>)}</div></section>}
    <section className="content-section location-card"><div className="store-visual"><img src={business.storeImageUrl} alt={business.name} /><span className="store-badge"><MapPin /> {business.locationLabel}</span></div><div className="store-details"><span className="eyebrow"><MapPin /> {business.storeHeading}</span><h2>{business.name}</h2><address>{business.address || business.locationLabel}</address>{business.storeStatus && <p className="store-status">● {business.storeStatus}</p>}{business.mapsUrl && <a href={business.mapsUrl} target="_blank" rel="noreferrer" className="maps-button"><Map /> Ouvrir dans Google Maps <ChevronRight /></a>}</div></section>
    <section className="utility-row"><button type="button" className="utility-button" onClick={share}><span><Share2 /></span><strong>Partager</strong><small>Cette carte</small></button><button type="button" className="utility-button" onClick={openQr}><span><QrCode /></span><strong>QR Code</strong><small>Scanner</small></button><button type="button" className="utility-button" onClick={() => copy(business.phone, "Numéro copié")}><span><Copy /></span><strong>Copier</strong><small>Le numéro</small></button>{business.mapsUrl && <a className="utility-button" href={business.mapsUrl} target="_blank" rel="noreferrer"><span><Map /></span><strong>Itinéraire</strong><small>Y aller</small></a>}</section>
    <footer><span /><p>{business.footerText}</p><span /></footer>
    {open && <div className="qr-overlay" role="presentation" onMouseDown={() => setOpen(false)}><section className="qr-sheet" role="dialog" aria-modal="true" aria-labelledby="qr-title" onMouseDown={(e) => e.stopPropagation()}><button className="qr-close-icon" type="button" aria-label="Fermer" onClick={() => setOpen(false)}><X /></button><header className="qr-header"><img className="sheet-logo" src={business.logoUrl} alt={business.name} /><h2 id="qr-title">Scan to connect</h2><p>Scannez pour ouvrir cette carte digitale.</p></header><div className="qr-frame">{qr && <img src={qr} alt={`QR code de ${business.name}`} />}</div><div className="qr-actions"><button className="copy-link" type="button" onClick={() => copy(window.location.href, "Lien copié")}><Copy /> Copier le lien</button><button className="close-sheet" type="button" onClick={() => setOpen(false)}>Fermer</button></div></section></div>}
    <div className={`app-toast${toast ? " is-visible" : ""}`} role="status" aria-live="polite">{toast}</div>
  </main>;
}
